Make `datapipe.py` compatible with `torchdata==0.11` or later (#10080)
With `torch 2.7`/`torchdata 0.11` releases, the `datapype.py` example
fails
```
python3 /workspace/examples/datapipe.py 
Traceback (most recent call last):
  File "/workspace/examples/datapipe.py", line 17, in <module>
    from torchdata.datapipes.iter import FileLister, FileOpener, IterDataPipe
ModuleNotFoundError: No module named 'torchdata.datapipes'
```
fails because some classes have been moved from `torchdata` to `torch`
nd a few methods, including in_memory_cache, have been removed.

The current PR resolves this issue in that example.

**NOTES:**
Running this example with the option `--task mesh` was failing even with
previous versions of `torch`/`torchdata` packages

- because 3991 out of 7981 are binary, not text files in the required
"OFF" format;
- if the  `meshio` and `torch_claster` packages are not installed. 

Proposed changes address both these issues.

---------

Co-authored-by: Serge Panev <spanev@nvidia.com>
Co-authored-by: Rishi Puri <puririshi98@berkeley.edu>
Co-authored-by: Akihiro Nitta <nitta@akihironitta.com>