Skip tests that require torch-cluster to be installed when it's not available (#9180)
These changes enable us to prevent the following test failures:
```
FAILED test/nn/models/test_dimenet.py::test_dimenet[DimeNet] - ImportError: 'radius_graph' requires 'torch-cluster'
FAILED test/nn/models/test_dimenet.py::test_dimenet[DimeNetPlusPlus] - ImportError: 'radius_graph' requires 'torch-cluster'
FAILED test/nn/models/test_gnnff.py::test_gnnff - ImportError: 'radius_graph' requires 'torch-cluster'
```