Use socket as context in tests including RPC to ensure better closing behaviors (CI fix) (#8574)
We've observed that removing DDP in #8563 helped to solve DDP-related
issues, however some RPC-related connection issues remain. This could be
due to `socket` module leaving the port open and `torch.rpc` finding the
port busy.
Using the socket as context to retrieve open port ID can help to solve
this.
Tested with CI 'Full testing' :
https://github.com/pyg-team/pytorch_geometric/actions/runs/7141727138/attempts/1
All attempts pass Linux-based tests. Tested 3 times.
Error msg:
```
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:51262 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:51262 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
Process SpawnProcess-15:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/pytorch_geometric/pytorch_geometric/test/distributed/test_dist_neighbor_sampler.py", line 202, in dist_neighbor_sampler_temporal
    init_rpc(
  File "/home/runner/work/pytorch_geometric/pytorch_geometric/torch_geometric/distributed/rpc.py", line 65, in init_rpc
    rpc.init_rpc(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/torch/distributed/rpc/__init__.py", line 176, in init_rpc
    store, _, _ = next(rendezvous_iterator)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:51262 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:51262 (errno: 98 - Address already in use).
```

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>