Fix bug in `to_scipy_sparse_matrix` (#9146)
Setting the default device in PyTorch to "cuda" can cause a bug in the
`to_scipy_sparse_matrix` function.

Code to reproduce:
```python
import torch

from torch_geometric.utils import to_scipy_sparse_matrix

torch.set_default_device("cuda")

edge_index = torch.tensor([
    [0, 1, 1, 2, 2, 3],
    [1, 0, 2, 1, 3, 2],
])

to_scipy_sparse_matrix(edge_index)
```

All tensor input to the function is always copied to the CPU for further
processing. However, if `edge_attr` argument is **not** given to the
`to_scipy_sparse_matrix` function, a tensor of ones is created instead.
No device argument is specified currently for the creation of this
tensor, causing it to be created on the GPU if that is the default
setting. Almost directly after, `edge_attr.numpy()` is called, causing
the following error:
```
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

This pull request simply adds the `device="cpu"` argument to the
creation of the `edge_attr` tensor to prevent this.