Fix RPC timeout issues caused by premature worker closing (#8637)
This PR fixes RPC-related errors caused by premature worker shutdown. 
Closed #8605 and opened this PR to align with changes in #8503.

The cause were multiple `atexit` statements defined both in
`worker_loop` and in `rpc.py` that lead to unpredicatable behaviors
resulting in errors, when the `ConcurrentEventLoop` shutdown was lagging
behind.
```
RuntimeError: EPIPE: broken pipe (this error originated at tensorpipe/transport/uv/connection_impl.cc:157)
[W tensorpipe_agent.cpp:725] RPC agent for mp_sampling_worker-13 encountered error when reading incoming request from mp_sampling_worker-6: pipe closed (this error originated at tensorpipe/core/pipe_impl.cc:356)
```
Also I've removed `rpc_workers_names` from loader args as we're not
using that in current implementation.
Updated tests for the sampler.

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: Matthias Fey <matthias.fey@tu-dortmund.de>