Support symbolic tracing of `SchNet` (#5938)
This PR removes/modifies a couple control flow patterns that were used
in the `SchNet` implementation that are not traceable with `torch.fx`:

* removing the assertion in the forward pass
* Replaced calling `scatter` directly with an `Aggregation` module

Without these changes, attempting symbolic tracing:
```
from torch_geometric.nn.fx import Transformer
from torch_geometric.nn import SchNet

model = SchNet()
tx = Transformer(model, debug=True)
tx.transform()
```

fails with:
```
TraceError: symbolically traced variables cannot be used as inputs to control flow
```

Co-authored-by: rusty1s <matthias.fey@tu-dortmund.de>