Fixed bug in `utils.bipartite_subgraph` (#6654)
The PR fixes a bug in the `utils.bipartite_subgraph` method, which
crashes if `src_subset` contains Boolean values but `dst_subset`
contains integers.

Consider the following example:
```python
import torch
from torch_geometric.utils import bipartite_subgraph

subset = (torch.tensor([True, True, False]), torch.tensor([0, 3]))
edge_index = torch.tensor([[0, 1, 2], [0, 0, 3]])
sub_edge_index = bipartite_subgraph(subset, edge_index)
```
With torch_geometric==2.3.0 we obtain the following error:
```
Traceback (most recent call last):
  File "/home/jan/git/gerd/pygtest.py", line 8, in <module>
    sub_edge_index = bipartite_subgraph(subset, edge_index)
  File "/home/jan/miniconda3/envs/gerd/lib/python3.9/site-packages/torch_geometric/utils/subgraph.py", line 178, in bipartite_subgraph
    edge_mask = src_subset[edge_index[0]] & dst_subset[edge_index[1]]
IndexError: index 3 is out of bounds for dimension 0 with size 2
```
The method determines whether or not a cast of the masks is needed by
only checking the dtype of the source mask, which causes this issue.

While this seems like a rare edge case, this issue does cause the
`HeteroData.subgraph` method to crash when `subset_dict` uses Boolean
masks and does not contain some ntypes as keys, as integer tensors are
then added for the missing ntypes.

Since https://github.com/pyg-team/pytorch_geometric/pull/6218,
`HeteroData.subgraph` does retain ntypes that are absent from
`subset_dict`. I have also updated the doc string of the method to
reflect this change, since it was still describing the previous
behavior.

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: toensoff <toenshoff@informatik.rwth-aachen.de>
Co-authored-by: Jinu Sunil <jinu.sunil@gmail.com>