default to None for input_ids, fixes cugraph failures (#8394)
```
713E File "/opt/rapids/cugraph/python/cugraph-pyg/cugraph_pyg/loader/cugraph_node_loader.py", line 511, in __iter__ 
714E self.current_loader = EXPERIMENTAL__BulkSampleLoader(
715E File "/opt/rapids/cugraph/python/cugraph-pyg/cugraph_pyg/loader/cugraph_node_loader.py", line 151, in __init__ 
716E input_type, input_nodes = torch_geometric.loader.utils.get_input_nodes(
717E TypeError: get_input_nodes() missing 1 required positional argument: 'input_id'
```