Fix txt2kg handling of non-retryable NIM API errors (#10771)
After running `test_txt2kg_rag.py` for more than two hours, we
encountered the following error:
```Note that if the TXT2KG process is too slow for you're liking using the public NIM, consider deploying yourself using local_lm flag of TXT2KG or using https://build.nvidia.com/nvidia/llama-3_1-nemotron-70b-instruct to deploy to a private endpoint, which you can pass to this script w/ --ENDPOINT_URL flag.
Guide for deploying NIM: https://developer.nvidia.com/blog/a-simple-guide-to-deploying-generative-ai-with-nvidia-nim/
Extracting KG triples:   0%|                                                                                                                       | 0/4 [00:00<?, ?it/s]Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'
```

Following a thorough investigation, we determined that the issue was
caused by the expiration of the **`NV_NIM_KEY`**, while the program's
prolonged operation was due to numerous attempts to restart the workers.

Since the call stack captured at the time of the failure did not point
to the root cause—which could have been identified during the initial
worker startup attempt—we decided to improve the error-handling
mechanism for NIM errors where operation retries are not applicable.

This PR adjusts the error handling and retry logic for `txt2kg`'s
multi-process execution:

* Disables retries for API errors that do not support retrying (e.g.,
HTTP 403).
* Passes error information from workers in a `pickle`-compatible format
instead of passing OpenAI exceptions across processes.
* Prevents `multiprocessing.RemoteTraceback` errors and associated hangs
when handling worker failures.
* Reports potential issues with the **`NV_NIM_KEY`** used for the test.


Errors are reported in the following format:
```
[Worker 0] attempt 1/200: PermissionDeniedError: Error code: 403 - {'status': 403, 'title': 'Forbidden', 'detail': 'Authorization failed'}. Retryable=False

 ***** Please, check your NV_NIM_KEY. *****
The key may be expired, invalid or not authorized to access the dataset you are using.

[Worker 1] attempt 1/200: PermissionDeniedError: Error code: 403 - {'status': 403, 'title': 'Forbidden', 'detail': 'Authorization failed'}. Retryable=False

 ***** Please, check your NV_NIM_KEY. *****
The key may be expired, invalid or not authorized to access the dataset you are using.
```

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>