Destroy process group in `graphgym` test (#9598)
When `test_graphgym.py::test_train` is executed, a process group is
created. If this group is not properly destroyed, it can interfere with
subsequent tests, causing failures such as:
```
FAILED ../../pytorch_geometric/test/metrics/test_link_pred_metric.py::test_precision[1-32-3000-1000-100] - RuntimeError: No backend type associated with device type cpu
FAILED ../../pytorch_geometric/test/metrics/test_link_pred_metric.py::test_precision[10-32-3000-1000-100] - RuntimeError: No backend type associated with device type cpu
FAILED ../../pytorch_geometric/test/metrics/test_link_pred_metric.py::test_precision[100-32-3000-1000-100] - RuntimeError: No backend type associated with device type cpu
FAILED ../../pytorch_geometric/test/metrics/test_link_pred_metric.py::test_recall - RuntimeError: No backend type associated with device type cpu
FAILED ../../pytorch_geometric/test/metrics/test_link_pred_metric.py::test_f1 - RuntimeError: No backend type associated with device type cpu
FAILED ../../pytorch_geometric/test/metrics/test_link_pred_metric.py::test_map - RuntimeError: No backend type associated with device type cpu
FAILED ../../pytorch_geometric/test/metrics/test_link_pred_metric.py::test_ndcg - RuntimeError: No backend type associated with device type CPU
```
A similar bug was recently fixed by
[PR#9534](https://github.com/pyg-team/pytorch_geometric/pull/9534).

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: rusty1s <matthias.fey@tu-dortmund.de>